# -*- coding: utf-8 -*-
"""testfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrLTNqODB1Z9BbsyZ9kA_kDhSG5xYAIm
"""



import numpy as np
import librosa, librosa.display
import matplotlib.pyplot as plt
import math


file = "path of the wav file to be tested"

# load audio file with Librosa
signal, sample_rate = librosa.load(file, sr=22050)
data = {
        "mapping": [],
       
    }






hop_length = 512 # in num. of samples
n_fft = 2048 # window in num. of samples
SAMPLE_RATE = 22050
TRACK_DURATION = 7 # measured in seconds
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION

samples_per_segment = int(SAMPLES_PER_TRACK / 10)
num_mfcc_vectors_per_segment = math.ceil(samples_per_segment / hop_length)



# calculate start and finish sample for current segment
start = 0
finish = start + samples_per_segment
                    
mfcc = librosa.feature.mfcc(signal[start:finish], sample_rate, n_mfcc=13, n_fft=n_fft, hop_length=hop_length)
mfcc = mfcc.T

if len(mfcc) == num_mfcc_vectors_per_segment:
      data["mfcc"].append(mfcc.tolist())
                        
z=np.array(data["mfcc"])

z= z[..., np.newaxis]
print(z[0].shape)